-- MySQL Script generated by MySQL Workbench
-- Fri Dec  4 00:05:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbfastparking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbfastparking` ;

-- -----------------------------------------------------
-- Schema dbfastparking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfastparking` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `dbfastparking` ;

-- -----------------------------------------------------
-- Table `dbfastparking`.`tblcliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbfastparking`.`tblcliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dbfastparking`.`tblcliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `placacarro` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `nomecliente` VARCHAR(45) NOT NULL,
  `horaentrada` TIME NOT NULL,
  `horasaida` TIME NULL,
  `comprovante` TEXT NULL,
  `tblclientecol` VARCHAR(45) NULL,
  `statuscliente` TINYINT NULL,
  `idpreco` INT NULL,
  PRIMARY KEY (`idcliente`),
  CONSTRAINT `idpreco`
    FOREIGN KEY (`idpreco`)
    REFERENCES `dbfastparking`.`tblpreco` (`idpreco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `idpreco_idx` ON `dbfastparking`.`tblcliente` (`idpreco` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dbfastparking`.`tblpreco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbfastparking`.`tblpreco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dbfastparking`.`tblpreco` (
  `idpreco` INT NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NULL,
  `hora` VARCHAR(45) NULL,
  PRIMARY KEY (`idpreco`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dbfastparking`.`tblvaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbfastparking`.`tblvaga` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dbfastparking`.`tblvaga` (
  `idvaga` INT NOT NULL AUTO_INCREMENT,
  `numerovagas` INT NULL,
  `blocos` VARCHAR(1) NULL,
  PRIMARY KEY (`idvaga`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
